/**
 * scopeMatcher.js
 *
 * Pure, deterministic classifier that answers "does this legendary effect
 * buff this DPS champion?" It is the runtime kernel of the forge-run
 * optimizer specified in PRD §3.2.
 *
 * Inputs come from the bundled data files generated by scripts/refresh-defs.js:
 *   - scope records from data/definitions.legendary-effect-scopes.json
 *   - hero records from data/definitions.heroes.json
 *
 * Both are documented schemas (PRD §3.2.2 and §4.2). This module has no I/O,
 * no DOM, and no network dependencies — it's importable from both the browser
 * (native ES module) and from Node (via `node --test`).
 *
 * Scope record:
 *   { id: number,
 *     kind: "global" | "race" | "gender" | "alignment" | "damage_type"
 *         | "stat_threshold" | "unknown",
 *     value?: string,       // for race/gender/alignment/damage_type, canonical case
 *     stat?: string,        // for stat_threshold: "str"|"dex"|"con"|"int"|"wis"|"cha"
 *     min?: number }        // for stat_threshold
 *
 * Hero record (fields the matcher reads):
 *   { tags: string[]            // lowercased, pre-tokenized by the API
 *     damage_types: string[]    // subset of ["melee","ranged","magic"]
 *     ability_scores: { str, dex, con, int, wis, cha } }
 *
 * Any missing hero field is treated as "does not match" (defensive; never
 * throws). This lets the matcher tolerate partial fixture data in tests and
 * future schema evolution without cascading runtime errors into the UI.
 */

/**
 * True if `scope` affects `hero`.
 *
 * Semantics (PRD §3.2.2):
 *   global         → always true
 *   race/gender/alignment → scope.value (lowercased) ∈ hero.tags
 *   damage_type    → scope.value (lowercased) ∈ hero.damage_types
 *   stat_threshold → hero.ability_scores[scope.stat] >= scope.min
 *   unknown        → false (conservative; flagged upstream for parser
 *                    extension via data/definitions.checksum.json's
 *                    unknown_scope_ids)
 *
 * @param {object} scope — a scope record (see module docstring)
 * @param {object} hero  — a hero record (see module docstring)
 * @returns {boolean}
 */
export function effectAffectsHero(scope, hero) {
  if (!scope || !hero) return false;

  switch (scope.kind) {
    case 'global':
      return true;

    case 'race':
    case 'gender':
    case 'alignment': {
      const tags = hero.tags;
      if (!Array.isArray(tags) || typeof scope.value !== 'string') return false;
      return tags.includes(scope.value.toLowerCase());
    }

    case 'damage_type': {
      const types = hero.damage_types;
      if (!Array.isArray(types) || typeof scope.value !== 'string') return false;
      return types.includes(scope.value.toLowerCase());
    }

    case 'stat_threshold': {
      const scores = hero.ability_scores;
      if (!scores || typeof scope.stat !== 'string' || typeof scope.min !== 'number') {
        return false;
      }
      const have = scores[scope.stat.toLowerCase()];
      return typeof have === 'number' && have >= scope.min;
    }

    case 'unknown':
    default:
      return false;
  }
}

/**
 * The sorted set of effect ids whose scope affects `hero`.
 *
 * The result is sorted ascending by id, which matches the sort order of
 * the generated scope bundle; downstream UI can render in this order
 * without its own sort pass.
 *
 * @param {object[]} scopes — an array of scope records
 * @param {object} hero     — a hero record
 * @returns {number[]}
 */
export function affectingEffectIds(scopes, hero) {
  if (!Array.isArray(scopes) || !hero) return [];
  const ids = [];
  for (const scope of scopes) {
    if (effectAffectsHero(scope, hero)) ids.push(scope.id);
  }
  ids.sort((a, b) => a - b);
  return ids;
}
